### ISSUE TITLE
SQL Editor throws errors

### ISSUE THREAD

**Issue by juzhiyuan** [motifland/markprompt#10]
Hi, 

Thanks for making such a great service!

When I try to follow this action:

> The schema is defined in [schema.sql](https://github.com/motifland/markprompt/blob/main/config/schema.sql). Create a Supabase database and paste the content of this file into the SQL editor. Then run the Typescript types generation script using:

Supabase throws an error: 

<img width="679" alt="image" src="https://user-images.githubusercontent.com/2106987/227784942-ab5a0f26-d210-4ce3-8738-beb086daf8b4.png">

Can anyone help with what's wrong with here?

**Comment by michaelfester** [comment]
Hi @juzhiyuan! Can you try to paste the queries one query at a time as opposed to the entire file at once? I've noticed sometimes the SQL editor complains when you give it many statements.

**Comment by juzhiyuan** [comment]
Thanks! It works
