### ISSUE TITLE
File synchronisation: add filter on path

### ISSUE THREAD

**Issue by antmonnier** [motifland/markprompt#11]
It should be possible to synchronise a subset of MD files in a repository.

Use cases:

- Discard non-content project files, such as `README.md`.
- Create one project per language in the repository, eg we want to include all files in `/content/fr`.

Suggestion: use the [glob pattern language](https://en.wikipedia.org/wiki/Glob_(programming)) to specify a pattern of files to include, at the project level.

**Comment by michaelfester** [comment]
Yes, on the roadmap.

**Comment by michaelfester** [comment]
Hi @antmonnier, just shipped: https://github.com/motifland/markprompt/pull/30.

Docs here: https://markprompt.com/docs#configuration.

Would love your feedback!

**Comment by antmonnier** [comment]
Thanks! One note: files synced before setting an exclude pattern show up in the Data section even if they don't match. I had to delete all files and sync the whole repo again.

**Comment by michaelfester** [comment]
Thanks for the feedback. Yes the filters apply at upload/sync time. Once processed, we won't delete the files even if the configuration changes, so you would need to delete the files and sync again. We could indeed add a CTA to explicitly prune and resync the project.
