### ISSUE TITLE
[Bug] POST https://markprompt.com/api/github/fetch replies with 500

### ISSUE THREAD

**Issue by antmonnier** [motifland/markprompt#12]
When I click on "Sync repo" in the "Data" page, nothing happens.

The console shows this:

![image](https://user-images.githubusercontent.com/5095197/227920527-01625f49-2dda-4013-9623-1f1b979e582e.png)

**Comment by michaelfester** [comment]
Does this happen right after you click on "Sync repo", or after a while? Could you send me the URL of the public repo so I can test it out? Thanks!

**Comment by michaelfester** [comment]
Ok, fix has been deployed: https://github.com/motifland/markprompt/commit/85aa70c3bc46365fc0fbd63bf3cf06b316a12241

**Comment by antmonnier** [comment]
Git repo: https://github.com/HubRise/website

After your fix, I'm now getting a different error message, this time not immediately but after a few seconds.

![image](https://user-images.githubusercontent.com/5095197/228032844-0e2319b5-903f-47af-8344-702bf620c3c1.png)

**Comment by michaelfester** [comment]
Strange, seems like your connection timed out. I was able to make it work here. Can you refresh and try again?

<img width="1309" alt="CleanShot 2023-03-27 at 12 15 53@2x" src="https://user-images.githubusercontent.com/504893/228043900-81f26250-8802-4f51-a9c9-fd093c22773c.png">

**Comment by antmonnier** [comment]
After a few tries, it worked eventually. Thanks!

**Comment by michaelfester** [comment]
I would like to get to the bottom of this. How long did it take before the "Processing..." messages started coming in?

**Comment by antmonnier** [comment]
Couldn't tell reliably. I tried a few times, with the markprompt tab in the background. Sorry that I cannot be more helpful.

**Comment by michaelfester** [comment]
Ok, let me know if anything comes up.
