### ISSUE TITLE
train my repository, report this error that Error: Failed to download repository. Make sure the "main" or "master" branch is accessible, or specify a branch explicitly.

### ISSUE THREAD

**Issue by ydaydayup** [motifland/markprompt#184]
**Describe the bug**

Error processing repo ydaydayup/myblog: Error: Failed to download repository. Make sure the "main" or "master" branch is accessible, or specify a branch explicitly.

**To Reproduce**

1. add your repository, and make sure you have add your branch which is existed and can be got
2.  click this button: train

**Expected behavior**

**Screenshots**
![image](https://github.com/motifland/markprompt/assets/51449469/ec375f4b-7d97-4edb-b952-08a0bd9ebdcb)
**Desktop (please complete the following information):**

- Browser chrome

**Additional context**

**Comment by michaelfester** [comment]
Thanks for this! I just pushed a tentative fix: https://github.com/motifland/markprompt/commit/0ddb81601135fe042d1cf6ba7506a2b045ada87b.

Could you please try again and let me know if the problem persists?

**Comment by johnd0e** [comment]
I can confirm that the issue is gone
