### ISSUE TITLE
Installing npm dependencies fails due to different required react types versions

### ISSUE THREAD

**Issue by ThomasKirst** [motifland/markprompt#2]
Hi there 👋

I wanted to give this a try installing it locally. After having cloned the repository I ran `npm install`.

Unfortunately, I got this error:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: markprompt@0.1.0
npm ERR! Found: @types/react@18.0.28
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"18.0.28" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^17.0" from @team-plain/react-chat-ui@6.2.3
npm ERR! node_modules/@team-plain/react-chat-ui
npm ERR!   @team-plain/react-chat-ui@"^6.2.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

It seems as if the main app requires `@types/react` in version 18 whereas the `react-chat-ui` module requires an older version (17).

I am using node version 18.15.0 (LTS).

Is there an easy way to fix this or did I miss anything?

Thanks in advance :)
– Thomas

**Comment by michaelfester** [comment]
Hi Thomas, can you try the latest version 0.1.5?

**Comment by ThomasKirst** [comment]
Hi Michael, not quite sure about the package.json.

The outer package.json on main reads:

```json
{
  "name": "markprompt",
  "version": "0.1.0",
  ...
}
```

The [inner package.json](https://github.com/motifland/markprompt/blob/main/packages/markprompt-react/package.json) has the same package name but version `0.1.5`.

I tried to `npm install` inside, which worked, but it is only a module, not the main app, as far as I understand.
I got the same error again when I tried to install it on the root directory (all on the current `main`).

**Comment by michaelfester** [comment]
Ah right, will need to fix the setup for npm. It should work with yarn. Could you please try this and let me know?

**Comment by ThomasKirst** [comment]
Yes, with `yarn` I got this result:

```bash
~/Dev/markprompt main ❯ yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning swr@2.1.0: The engine "pnpm" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning " > @mdx-js/loader@2.3.0" has unmet peer dependency "webpack@>=4".
warning " > @team-plain/react-chat-ui@6.2.3" has incorrect peer dependency "@types/react@^17.0".
warning " > @team-plain/react-chat-ui@6.2.3" has incorrect peer dependency "@types/react-dom@^17.0".
warning " > @team-plain/react-chat-ui@6.2.3" has incorrect peer dependency "react@^17.0".
warning " > @team-plain/react-chat-ui@6.2.3" has incorrect peer dependency "react-dom@^17.0".
warning "@team-plain/react-chat-ui > goober@2.1.9" has incorrect peer dependency "csstype@^3.0.10".
warning "react-hot-toast > goober@2.1.12" has unmet peer dependency "csstype@^3.0.10".
[4/4] 🔨  Building fresh packages...
✨  Done in 49.98s.
```

In this case, I received just warnings instead of errors, still concerning the different React versions.

**Comment by remcohaszing** [comment]
This project uses yarn, not npm. I understand warnings are annoying, but they’re just warnings. It’s working as intended for markprompt.
