### ISSUE TITLE
Error: PlainProvider needs to be initialised with a valid appKey and getCustomerToken method!

### ISSUE THREAD

**Issue by kanertuncel** [motifland/markprompt#21]
I'm receiving this error. I created app and secret key twice and double checked the keys. Which information is required to investigate the issue? 

```
Unhandled Runtime Error
Error: PlainProvider needs to be initialised with a valid appKey and getCustomerToken method!

Call Stack
PlainProvider
node_modules/@team-plain/react-chat-ui/dist/components/provider.js (43:0)

```

**Comment by michaelfester** [comment]
Hi @kanertuncel. Did you also enable chat in the Plain dashboard?

**Comment by kanertuncel-nu3** [comment]
Yes, everything seems fine, today i'll talk to someone from plain and write here if i proceed on any progress. Thanks

**Comment by michaelfester** [comment]
Ok great!
