### ISSUE TITLE
Standalone component

### ISSUE THREAD

**Issue by antmonnier** [motifland/markprompt#23]
To ease adoption, it would be helpful to make Markprompt usable via a form hosted on your service. Pretty much like the playground, but without the need to login, and with nothing but the form. This could also be a good means to promote your service, as the page could include your logo.

Security would be provided through the use of an hard-to-guess URL (which is fine for public documentation for example) + `noindex` meta field. For added security, the "Generate a link to search the documentation anonymously" option should be explicitly enabled from the Settings.

**Comment by michaelfester** [comment]
That's a great idea! Will see how we can set this up! 👍

**Comment by michaelfester** [comment]
This has now been shipped: https://github.com/motifland/markprompt/pull/73
