### ISSUE TITLE
Doesn't process large markdown files

### ISSUE THREAD

**Issue by Gdewilde** [motifland/markprompt#25]
When trying out Markprompt it doesn't look like it's picking up large (>4MB) markdown files like https://raw.githubusercontent.com/apideck-io/third-party-api-docs/main/markdown/magento.md

<img width="1728" alt="Screenshot 2023-04-05 at 19 03 32" src="https://user-images.githubusercontent.com/1112129/230152862-439e8f8b-3931-413d-b536-5e926c44ea30.png">

**Comment by michaelfester** [comment]
Hi @Gdewilde! Yes there is hard limit of [4.5MB on the request body side](https://vercel.com/docs/concepts/limits/overview#functions-comparison). I think the most appropriate solution would be to set up a proxy on the training endpoint that takes care of chunking up large files, as it needs to work both on the dashboard and for API calls.

**Comment by Gdewilde** [comment]
Hi @michaelfester, thanks for the quick reply. Shouldn't the UI return an error message for this?

**Comment by michaelfester** [comment]
It should indeed. Just added a message on the screen. Thanks for pointing it out!
