### ISSUE TITLE
Hitting Up GitHub API rate limit

### ISSUE THREAD

**Issue by Bhupesh-V** [motifland/markprompt#3]
I tried using https://github.com/Bhupesh-V/til on the hosted version

Following issue was raised

<img width="1190" alt="Screenshot 2023-03-25 at 9 09 14 PM" src="https://user-images.githubusercontent.com/34342551/227727379-f5eeb52c-9052-4086-b31c-64b17f640456.png">

More info: https://twitter.com/bhupeshimself/status/1639651355211206656?s=20

**Comment by michaelfester** [comment]
Hi @Bhupesh-V yes addressing this today. As a workaround, just can download the repo and drag and drop the folder at once. We just did it we a 700-files repo and it worked smoothly.

**Comment by michaelfester** [comment]
Addressed this here: https://github.com/motifland/markprompt/commit/0df1d964987ad75c35608ce3eb05e43aee4e01df
