### ISSUE TITLE
Improving query results

### ISSUE THREAD

**Issue by antmonnier** [motifland/markprompt#31]
The purpose of this issue is to document some reproducible test cases in an effort to improve the algorithm. The MarkPrompt team can reuse the content of my repo, along with the prompt below, in their test scenarios. If you want to add your own test cases, please make sure you are fine with this too.

Here is a first case. I suggest following the pattern below to add your own test cases.

- **Repository**: https://github.com/HubRise/website
- **Prompt**: `How to create an order using the HubRise API?`
- **Reply**: `Sorry, I am not sure how to answer that.`
- **Why this could be improved**: Vanilla GPT-4 (which was pretrained on the repo), can answer very specifically to this query.

Idea: the answer to the prompt above is spread over multiple sections and it seems that MarkPrompt just discarded all sections in this case, as none of them had sufficient overlap with the query. To fix this issue, maybe you should compute embeddings at every hierarchical level of the content, then find the relevant sections using a top down search: first identify the matching pages, then "zoom in" to chapters within these, then to sections. Chapters and sections which would have been discarded using the current algorithm get a score boost for belonging to a wider piece of content that "generally" matches the prompt. Just an intuition of course, don't know if there is a scientific approach for doing this, I'm no AI specialist :).

**Comment by antmonnier** [comment]
Some ideas to improve the algo in this [Twitter thread](https://mobile.twitter.com/wooing0306/status/1645092115914063872).

**Comment by michaelfester** [comment]
Thanks! Starting to tackle this soon.

**Comment by antmonnier** [comment]
I've just tried a few queries, which all resulted in "Sorry, don't know how to answer that". I've tried customizing the prompt to allow GPT-4 to use its existing knowledge, to no avail. Not sure if this is a temporary bug?

![image](https://github.com/motifland/markprompt/assets/5095197/c552f356-16cc-45cf-a11c-20b825df5c8d)

**Comment by michaelfester** [comment]
Do you see any references showing up? Is it the same behavior with the default template?

**Comment by antmonnier** [comment]
> Do you see any references showing up?

No it just says it has no answer.

> Is it the same behavior with the default template?

I've just tried with the default prompt. The question's explicit answer is on the first line of [this page](https://github.com/HubRise/website/blob/master/content/apps/3s-pos/en/overview.md), and this page has been pulled:

![image](https://github.com/motifland/markprompt/assets/5095197/88f1a3fb-6aeb-429b-83b1-0ab66f81efb4)

Answer:

![image](https://github.com/motifland/markprompt/assets/5095197/2a5b1671-8696-44d9-b68f-80a0062ed79b)

**Comment by antmonnier** [comment]
Hi @michaelfester 

Thanks for your investigation.

I can see the error message, thank you for adding this. A suggestion is to make it more obvious that the billing issue is on OpenAI side, not yours.

So I've removed my OpenAI key, but now I keep on getting "No relevant sections found" results, even on a simple question like the one above.

**Comment by michaelfester** [comment]
I relaunched the training of your project, and it seems to be returning answers now. It had erroneously marked your files as processed despite the fact that OpenAI had not processed them due to the rate limit. I pushed a fix that discards all files that have not been processed successfully. Let me know if you still see anything.

**Comment by michaelfester** [comment]
@antmonnier can you confirm this is now solved on your end? If so, I will close the issue.

**Comment by antmonnier** [comment]
@michaelfester Yeah works!

**Comment by michaelfester** [comment]
Ok great to hear!
