### ISSUE TITLE
Apparently basic query: "What is Legos" does not return an answer

### ISSUE THREAD

**Issue by epowell101** [motifland/markprompt#4]
We trained on the following document:
[Lego Docs](https://github.com/Fraud-Detection-and-Defense/lego-docs)

When we made queries in the sandbox we didn't get any responses, only:
"Sorry, I am not sure how to answer that."

Is this expected behavior?

**Comment by hb1998** [comment]
yesterday there were some issues, however, it seems to be fixed now. can you try it now

**Comment by michaelfester** [comment]
@epowell101 can you confirm this is working on your end? Also, now that we added a model selector in the playground, you can try if it's a shortcoming of the completions model.

**Comment by epowell101** [comment]
Great pace of advancement! Keep shipping 🫡.

Yes working w gpt-4!

Evan

Evan Powell
415 377 9812
Twitter: @epowell101 ( http://www.twitter.com/epowell101 )

**Comment by michaelfester** [comment]
Ok great, I will close the issue then.
