### ISSUE TITLE
Make the React component headless

### ISSUE THREAD

**Issue by michaelfester** [motifland/markprompt#42]
**Is your feature request related to a problem? Please describe.**
The React component should not come with any prescribed style. Similar to Radix UI and Headless UI, we should create the right abstractions allowing each part of the UI to be fully customized.

**Describe the solution you'd like**
I imagine a structure that looks like this (cf. https://www.radix-ui.com/docs/primitives/components/dialog for inspiration):

```jsx
const MarkpromptDemo = () => (
  <Markprompt.Root>
    <Markprompt.Trigger asChild>
      <button className="Button">Ask docs...</button>
    </Markprompt.Trigger>
    <Markprompt.Portal>
      <Markprompt.Overlay className="MarkpromptOverlay" />
      <Markprompt.Content className="MarkpromptContent">
        <Markprompt.Input className="MarkpromptInput" placeholder="Ask docs..."></Markprompt.Input>
        <Markprompt.Answer className="MarkpromptAnswer">
        </Markprompt.Answer>
        <Markprompt.References className="MarkpromptReferences">
           {({ name, path }) => (
            <a
              className="MarkpromptReference"
              href={path}
            >
              {name}
            </a>
          )}
        </Markprompt.References>
        <Markprompt.Close asChild>
          <button className="IconButton" aria-label="Close">
            <Cross2Icon />
          </button>
        </Markprompt.Close>
      </Markprompt.Content>
    </Markprompt.Portal>
  </Markprompt.Root>
);
```

**Comment by remcohaszing** [comment]
We could also make it a hook:

```tsx
export function MyComponent() {
  const [query, setQuery] = useState('')

  const { anwer, error, loading, references } = useMarkprompt(query)

  return (
    <>
      <input onChange={event => setQuery(event.currentTarget.value)} />
      <div>
        {answer}
      </div>
    </>
  )
}
```

This way we don’t have to deal with any UI at all, giving the user full control.

**Comment by nickrttn** [comment]
Why not both?

**Comment by remcohaszing** [comment]
Sure, we can support both. We should really consider the public interface though. I personally have my doubt about the added value of a component of we already provide such a hook though. Also it’s additional maintenance.

**Comment by remcohaszing** [comment]
I think it also makes sense to add a provider for the API key:

```tsx
export function App() {
  return (
    <MarkpromptProvider projectKey="…">
      <MyComponent />
    </MarkpromptProvider>
  )
}
```

**Comment by nickrttn** [comment]
What is the added value there? I imagine most folks will likely end up with something like

```tsx
<Markprompt projectKey={process.env.MARKPROMPT_PROJECT_KEY} …other options… />`
```

A context provider would just create additional React overhead no?

**Comment by remcohaszing** [comment]
This means the user would just define the project key once. It can then use the Markprompt hook / component anywhere in the project without having to specify it each time.
