### ISSUE TITLE
Switch between projects

### ISSUE THREAD

**Issue by antmonnier** [motifland/markprompt#43]
**Is your feature request related to a problem? Please describe.**
Switching from one project to another currently requires going through the main Projects page.

**Describe the solution you'd like**
Replace the static project name in the screenshot below by a dropdown, in the same way as "Personal". The dropdown will let the user switch between projects.
![image](https://user-images.githubusercontent.com/5095197/231971624-9a34f234-57b2-44ef-bca7-89b812e2e8fa.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by michaelfester** [comment]
Added project switcher here: https://github.com/motifland/markprompt/pull/26

<img width="654" alt="CleanShot 2023-04-18 at 11 50 23@2x" src="https://user-images.githubusercontent.com/504893/232875174-41db4ac2-745f-407a-aaab-ef9cc24a3c57.png">
