### ISSUE TITLE
I copied schema.sql to the Supabase SQL editor, but after running it, an error occurred: Invalid SQL query.

### ISSUE THREAD

**Issue by zsodur** [motifland/markprompt#57]
**Describe the bug**
I copied schema.sql to the Supabase SQL editor, but after running it, an error occurred: Invalid SQL query.

**Screenshots**
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/23167878/233775600-72a8ae23-435f-4449-9b91-c20222c13f87.png">

**Comment by michaelfester** [comment]
Thanks for this! Fix has been pushed: https://github.com/motifland/markprompt/pull/58
