### ISSUE TITLE
Allow customisation of the completion template

### ISSUE THREAD

**Issue by antmonnier** [motifland/markprompt#7]
The completion template is currently hardcoded to `You are a very enthusiastic company representative ... ${contextText} ... ${sanitizedQuery} ...`

Would be nice to be able to customise it, in order to provide more directions, or use a different language.

**Comment by michaelfester** [comment]
This is now live. Here are the docs: https://markprompt.com/docs#templates.

Note that this can also be used for internationalization and custom business logic, as shown in the docs examples.

**Comment by antmonnier** [comment]
@michaelfester sorry for commenting in a closed issue. I think this customisation should also be available as a project setting, not just via the API. This will be useful when you support standalone components (#27).

**Comment by michaelfester** [comment]
Agreed. Wanted to ship the API now though, without waiting for the dashboard interface.

**Comment by michaelfester** [comment]
Created a separate issue for this: https://github.com/motifland/markprompt/issues/48
