### ISSUE TITLE
Playground: add a model selector

### ISSUE THREAD

**Issue by antmonnier** [motifland/markprompt#8]
The playground uses the `gpt-3.5-turbo` model by default.

Would be nice to be able to select another model, to find which one works the best.

**Comment by michaelfester** [comment]
Good idea, will add!

**Comment by michaelfester** [comment]
Added: https://github.com/motifland/markprompt/commit/c4960b9520567dcd33f0703daa5d703179942c88

<img width="556" alt="CleanShot 2023-03-27 at 14 16 58@2x" src="https://user-images.githubusercontent.com/504893/228068769-5787b47e-4340-453e-a012-82e3ab76dfc1.png">
