### ISSUE TITLE
Data page: show full paths, and sort alphabetically

### ISSUE THREAD

**Issue by antmonnier** [motifland/markprompt#9]
Paths are not fully visible:

![image](https://user-images.githubusercontent.com/5095197/227783816-ab394212-9a32-4a62-919b-a114c813a63d.png)

Suggestions: increase the column width, or add a tooltip.

Would also make sense to sort them alphabetically, so that they appear in the same order as in a file editor.

**Comment by michaelfester** [comment]
Thanks @antmonnier! Yes, I think a proper file browser would be suitable here.

**Comment by michaelfester** [comment]
Added:
- Wider data table layout
- Sorting on name, path and date
- Tooltip on hover over path
